### ISSUE TITLE
デプロイ構成

### ISSUE THREAD

**Issue by Enchan1207** [Enchan1207/hono_rpc_sample#16]
## why

フロントエンドの環境切り替えできてなくない?

## how

環境で自動的にバックエンドのURLを設定するように。ついでに自動デプロイもやる

## tasks

- [x] バックエンドurlの自動振り分け
- [x] デプロイ自動化

**Comment by Enchan1207** [comment]
`client.ts` の `env.VITE_BACKEND_URL` は `process.env` も読み取ってくれるっぽいので、prodのURLはactions secretで渡してあげればいいと思う

**Comment by Enchan1207** [comment]
無理にprodのURL隠すよりZTAとかで防御した方がマシじゃないですか?

**Comment by Enchan1207** [comment]
ZTAの設定がかなりわからなくて困った、現状APIサーバとフロントと両方を一つのアプリケーションとして管理してて保護できてはいそうだけど

**Comment by Enchan1207** [comment]
……これもしかしてアプリケーション側でCORS設定しなくていい説あるか??

**Comment by Enchan1207** [comment]
ちょっとよくわかんない！とりあえずZTAで保護はできてるから、一旦デプロイ構成してあとでゆっくりやろう

**Comment by Enchan1207** [comment]
ここから

![Image](https://github.com/user-attachments/assets/a70e81c4-80fe-4b84-9d2c-c15a4d2f40ce)

Workers周りの権限を有効化したAPIトークンを生成し

**Comment by Enchan1207** [comment]
ここで生成したトークンとアカウントIDとをsecretに登録する

```sh
gh secret set CF_ACCOUNT_ID --body '<account_id>'
gh secret set CF_API_TOKEN --body '<api_token>'
```

**Comment by Enchan1207** [comment]
そしてこう

```yml
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npm run -w backend deploy
```
